      <!-- span_12 -->   			                            
      <section class="primary row span_12">				                                    
       <article class="col span_10">
          <h2 class="block  black_line">Privacy Policy</h2>           
          <p class="article_block_text">PSI Web Tech has created this privacy policy (the "Site Policy") to demonstrate our commitment to the privacy of our web site visitors and the right of privacy throughout the Internet.  Privacy on this PSI Web Tech web site (the "Site") is of great importance to us. PSI Web Tech will treat your personal information in accordance with the privacy statement in place at the time of collection of such information, or as you otherwise consent. By using this Site, you are agreeing to the terms of the Site Policy. We reserve the right to change the Site Policy. Your continued use of this Site, including use after the posting of any changes to these terms, will be deemed acceptance by you of the Site Policy.</p>
					
					<p class="article_block_text">You will find information on the following topics within this Site Policy:</p>
					<ul>
						<li>> Collected Information</li>
						<li>> Cookies and Clear GIFs</li>
						<li>> Security</li>
						<li>> Third-Party Sites</li>
					</ul>
					
					<h3>Collection Information</h3>
					<h4>Anonymous Information</h4>
					<p class="article_block_text">You can visit the Site to read information about our company, products, and services without telling us who you are and without revealing any personal information. To improve the usefulness of our site, PSI Web Tech measures and analyzes non-identifying, usage, and volume statistical information from Site visitors in order to administer our Site, and to constantly improve the quality of our service and site performance.</p>					
					<p class="article_block_text">Information gathered may include, but is not limited to, the following: the activity of the Site visitor's browser when the visitor is viewing the Site; the site path of visitors; and the time visitors come to the Site. PSI Web Tech reserves the right to publish anonymous, aggregate summary information regarding its Site visitors for promotional purposes and as a representative audience for advertisers. Please note that this is not personal information, only general summaries of our visitors' usage of the Site.</p>
					<h4>Personally Identifiable Information</h4>
					<p class="article_block_text">You may wish to request information about our products and services or to contact us in general online. To facilitate the distribution of this content, you may be asked to provide information, such as, but not limited to, name, company phone number, e-mail address and address. PSI Web Tech may also ask you for further information about your activities however, this is information is provided by you on a voluntary basis only and is not required by us in order for you to use and enjoy our Site.</p>
					<h4>Information Use and Disclosure</h4>
					<p class="article_block_text">PSI Web Tech uses the information that we collect on the Site to contact you to further discuss your interest in our company, our services, and to send information regarding our company, such as marketing promotions and events. This information may also be used to improve the services we provide you. The information is collected and stored in a manner that is appropriate for the nature of the data that we collect, and the need to fulfill your request. This information is not provided to third parties for their own use, unless specifically authorized by you. Though we make every effort to preserve user privacy, we may need to disclose personal information when required by law, or in order to comply with a current judicial proceeding, a court order, or legal process served on the Site. We may store and process personal information in the United Kingdom or any other country in which we (or any of our Subsidiaries or agents) maintain facilities.</p>
					<h3>Cookies and clear GIFs</h3>
					<h4>What Are Cookies</h4>
					<p class="article_block_text">Cookies are files that Web servers place on an Internet user's computer that are designed to store basic information (such as visitor preferences). The use of cookies on this Site allows visitors to enjoy more seamless visits and more accurately measures visitor behavior on the Site. There are two types of cookies: session and persistent. Session cookies exist only during an Internet user's online session. They disappear from the user's computer when he/she closes the browser software. Persistent cookies remain on the user's computer after the browser has been closed. The cookies used on the Site do not identify you personally. They merely recognize your browser, unless you choose to identify yourself voluntarily. You may choose to identify yourself for any one of the following reasons: by asking the browser to remember your username and password, by responding to a promotional offer, or by personalizing a web page or requesting more information on a product or service. Otherwise you remain anonymous.</p>
					<h4>How PSI Web Tech Uses Cookies</h4>
					<p class="article_block_text">When you interact with the Site, we strive to make that experience easy and meaningful. When you come to our Site, a server uses cookies to improve your interaction with the Site by, for example, remembering your preferences. More specifically, PSI Web Tech uses cookies to measure your behavior on this Site and to save personal settings on specific pages. PSI Web Tech uses cookies to identify the fact that you are a prior Site visitor (whatever the case may be). Users who disable their Web browsers' ability to accept cookies will still be able to browse the Site; however, they may lose some of the functionality provided by the use of cookies.</p>
					<h4>Controlling Our Use of Cookies</h4>
					<p class="article_block_text">You have the ability to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. If you are using a public computer or do not otherwise want this information to be stored, you can select the appropriate radio button on the sign-in page, and this cookie will not be used. For further information about disabling cookies you can visit www.allaboutcookies.org. If you choose to decline cookies, you may not be able to sign in or use other interactive features of the Site and services that depend on cookies.</p>
					<h4>Security</h4>
					<p class="article_block_text">While we strive to protect your personal information, no data transmission over the Internet can be guaranteed to be totally secure and therefore we cannot ensure or warrant the security of any information you send to us. You send any information via this Site at your own risk.</p>
					<h4>Third party sites</h4>
					<p class="article_block_text">The Site contains links to other web sites.  PSI Web Tech is not responsible for the privacy practices or the content of these other web sites. Customers and/or visitors should check the privacy policy statements of these other web sites to understand their policies. Customers and visitors who access a linked site may be disclosing their private information. It is the responsibility of the user to keep such information private and confidential.</p>
					<h3>Contact Us</h3>
					<p class="article_block_text">If you have questions, concerns, or suggestions regarding our Privacy Policy, we can be reached using the contact information on our <a href="article.php?page=contact">Contact Us</a> page.</p>                  				            
        </article>        
                                                        			              			              			                            
      </section>    