      <!-- span_12 -->   			                            
      <section class="primary row span_12 about-content grey_line">				                                    
        <article class="col span_10">
          <h2 class="block  black_line">Terms and Conditions</h2>      
        <p class="article_block_text">PSI Web Tech may add to, change or remove any part, term or condition of these Terms, and any Content (as defined below), including, without limitation, product and service descriptions. By continuing to access and use the Site, you are indicating your acceptance of such changes. Please check these Terms periodically for changes.</p>                         
      		<h3>Privacy</h3>
      				<p class="article_block_text">PSI Web Tech will only use any personal information that you provide to PSI Web Tech in connection with your use of the Site and PSI Web Tech's products and services, in accordance with the terms of PSI Web Tech's privacy policy (the "Privacy Policy"). In this regard, you agree to the then-current version of the Privacy Policy that you can find and read <strong><a href="utility.php?page=privacy">here</a></strong>. You hereby agree that PSI Web Tech may use your personal information in accordance with the terms of the Privacy Policy.</p>

      				<h3>Use of Site</h3>
      				<p class="article_block_text">Subject to your compliance with these Terms, PSI Web Tech hereby grants you a limited, personal, revocable, non-transferable, non-sublicensable, and non-exclusive license to access the Site and use the information, text, images, graphics, user and visual interfaces, applications, software, product and service data sheets, operation and maintenance manuals, technical notes, documents, and other materials displayed on the Site (collectively, the "Content"), solely for your own personal internal business use, on the condition that such use is solely in accordance with the purposes for which PSI Web Tech makes the Site and Content available. You may not copy, modify, reproduce, publicly display or perform, distribute, or otherwise use the Content except as expressly set forth above. You may not remove any copyright or other proprietary notices from any Content. If you breach any term or condition of these Terms, your authorization to use the Site and Content automatically terminates without notice to you, and you must immediately destroy any copies of the Content in your possession.</p>
      				<h3>Password and Responsibilities</h3>
      				<p class="article_block_text">Certain areas of the Site may only open to you if you register. You must provide PSI Web Tech with accurate, complete and updated registration information. Failure to do so will result in the immediate termination of your registration and right of access to the corresponding areas. You are solely responsible for keeping your login name and password secure and confidential.</p>
      				
      				<p class="article_block_text">You are solely responsible and liable for all activity, including any misuse, that occurs under your login name and password. You agree to immediately notify PSI Web Tech of any unauthorized use of your password or any other breach of security. Each registration is for a single user only. You may not share your password or any other registration information with any other natural person or entity and you may not share or transfer your registration.</p>
      				<h3>Prohibitions</h3>
      				<p class="article_block_text">You hereby represent and warrant that you will not, and will not induce any third party to: (a) attempt to disable or circumvent any security mechanisms used by the Site or otherwise attempt to gain unauthorized access to any portion or feature of the Site or Content, or any other systems or networks connected to the Site, or to any server of PSI Web Tech or its third party service providers, by hacking, password "mining", or any other illegal means; (b) use any "deep-link", "page-scrape", "robot", "spider", or other automatic device, program, algorithm or methodology, or any comparable manual process, to access, acquire, copy, or monitor any portion of the Site or Content; (c) use any device, software or routine to interrupt or interfere with, or attempt to interrupt or interfere with, the proper operation and working of the Site, or with any other person's use of the Site; (d) breach any security measures implemented on the Site; (e) track or seek to trace any information on any other person who visits the Site; (f) use the Site or Content for, or in connection with, any illegal purpose, to solicit, facilitate, encourage, condone, or induce any illegal activity, or as otherwise prohibited by these Terms or applicable laws, rules or regulations, including, without limitation, laws applicable to the export of software and data; or (g) copy, modify, create a derivative work of, reverse engineer, decompile, or otherwise attempt to extract the source code of any proprietary software used to provide, maintain, or otherwise applicable to, the Site or Content, or otherwise made available to you in connection with the Site or Content.</p>
      				<h3>Indemnification</h3>
      				<p class="article_block_text">You hereby agree to defend, indemnify and hold each of the PSI Web Tech Parties (as defined below) harmless from and against, any and all losses, liabilities, damages, and/or claims (including, without limitation, attorneys' fees and costs) arising from your breach of these Terms or otherwise arising from your use or misuse of the Site or Content.</p>
      				<h3>Proprietary Rights</h3>
      				<p class="article_block_text">You hereby acknowledge and agree that PSI Web Tech and its licensors own all legal right, title and interest in and to the Site and Content, including, without limitation, any and all intellectual property and other proprietary rights (including, without limitation, all patent rights, copyright rights, trademark rights and trade secret rights) which subsist in the Site and Content (whether such rights are registered or unregistered, and wherever in the world those rights may exist). As between you and PSI Web Tech, all Content together with the design, structure, selection, coordination, expression, 'look and feel', and arrangement of the Site and Content, and the domain names, trademarks, service marks, proprietary logos and other distinctive brand features found on the Site and in the Content are all owned by PSI Web Tech or its licensors. Nothing in these Terms gives you any right to use any of PSI Web Tech's or its licensors' trade names, trade marks, service marks, logos, domain names, or other distinctive brand features. All rights not expressly granted by PSI Web Tech under these Terms are reserved. There are no implied rights.</p>
      				<h3>Feedback</h3>
      				<p class="article_block_text">If you send or transmit any communications, comments, questions, suggestions, or related materials to PSI Web Tech, whether by letter, e-mail, telephone, or otherwise ("Feedback"), suggesting or recommending changes to PSI Web Tech's Site or Content, including, without limitation, new features or functionality relating thereto, all such Feedback is, and will be treated as, non-confidential and non-proprietary. You hereby assign all right, title, and interest in, and PSI Web Tech is free to use, without any attribution or compensation to you, any ideas, know-how, concepts, techniques, or other intellectual property and proprietary rights contained in the Feedback, whether or not patentable, for any purpose whatsoever, including but not limited to, developing, manufacturing, having manufactured, licensing, marketing, and selling, directly or indirectly, software or other products and services using such Feedback. You understand and agree that PSI Web Tech is not obligated to use, display, reproduce, or distribute any such ideas, know-how, concepts, or techniques contained in the Feedback, and you have no right to compel such use, display, reproduction, or distribution.</p>
      				<h3>Third Party Web Sites</h3>
      				<p class="article_block_text">The Site may provide links to third party web sites ("<strong>Third Party Sites</strong>"). PSI Web Tech provides such links solely as a convenience to you. PSI Web Tech does not review, approve, endorse, or make any representations about such Third Party Sites, the companies or persons who own and/or operate them, or any information, products and services made available through such Third Party Sites, or any results that may be obtained from using them. You should exercise common sense and your own judgment, and if you decide to access any Third Party Sites linked to the Site, you do so entirely at your own risk, and you are solely responsible for your activities conducted in connection with such Third Party Sites. Your use of Third Party Sites is subject to the terms of use and privacy policies located on the linked to Third Party Sites which may be different from these Terms or PSI Web Tech's Privacy Policy.</p>
      				
      				<h3>Electronic Communications</h3>
      				<p class="article_block_text">Whenever you visit the Site or send e-mails to PSI Web Tech, you are communicating with PSI Web Tech electronically. For that reason, you also consent to receive communications from PSI Web Tech electronically. PSI Web Tech will communicate with you by e-mail, by posting notices on the Site or by such other means as PSI Web Tech may determine from time-to-time. You agree that all agreements, notices, disclosures and other communications that PSI Web Tech provides to you electronically satisfy any legal requirement that such communications be in writing, to the extent permitted by applicable law.</p>              				            
        </article>                                         			              			              			                            
      </section>   
      
      